industry_table = {
    "Events": "Foodservice",
    "Jewellery": "Service",
    "Fast Food": "Foodservice",
    "Electronics": "Service",
    "Entertainment": "Retail",
    "Home Appliance": "Products",
    "Professional Services": "Office",
    "Cleaning": "Service",
    "Accessories": "Service",
    "Super Market": "Retail",
    "Construction Material": "Service",
    "Hospitality": "Retail",
    "Music": "Retail",
    "Livestock": "Service",
    "Furniture": "Factory",
    "Supermarket": "Retail",
    "Printing": "Service",
    "Toys": "Retail",
    "Parking": "Service",
    "Home Improvements": "Retail",
    "Coffeeshop": "Foodservice",
    "Construction": "Service",
    "Full Service Restaurant": "Foodservice",
    "Novelties": "Retail",
    "Bars": "Factory",
    "Food Truck": "Foodservice",
    "Government Services": "Service",
    "Hypermarket": "Retail",
    "Textile": "Retail",
    "Communication Materials and Systems": "Retail",
    "100% Home Delivery": "Foodservice",
    "undefined": "Foodservice",
    "Vocational Services": "Service",
    "Personal Care": "Service",
    "Warehouse": "Service",
    "Catering": "Foodservice",
    "Department Store": "Retail",
    "Media": "Service",
    "Sports": "Retail",
    "Textiles": "Retail",
    "Bakery": "Foodservice",
    "Hunting": "Retail",
    "Security": "Service",
    "Sport Goods": "Retail",
    "Logistics": "Products",
    "Plumbing Services": "Service",
    "Gifts": "Retail",
    "E-Commerce": "Retail",
    "Bookstore": "Retail",
    "Equipment": "Retail",
    "Cooperative Branch": "Retail",
    "Motors": "Products",
    "Pets": "Service",
    "Weapons": "Retail",
    "General Store": "Retail",
    "Gas Station": "Retail",
    "FMCG": "Foodservice",
    "Vending Machines": "Retail",
    "Repair": "Service",
    "Convenience Store": "Foodservice",
    "Food Retail": "Retail",
    "Government": "Service",
    "Cooperative": "Retail",
    "Training": "Service",
    "Photography": "Service",
    "Telecom": "Service",
    "Oil & Gas": "Service",
    "Agricultural & Industrial Machines": "Retail",
    "Coworking Space": "Service",
    "Contracting": "Service",
    "Cooperative Wholesale": "Retail",
    "Healthcare": "Retail",
    "Discount Retail": "Retail",
    "Religious Services": "Service",
    "Food Hall": "Foodservice",
    "Fast Casual": "Foodservice",
    "Smoking": "Products",
    "Cafe": "Foodservice",
    "Staffing": "Service",
    "Buffet": "Foodservice",
    "Technology": "Service",
    "Farming": "Retail",
    "Laundry": "Service",
    "Apparel": "Retail",
    "Property Management": "Service",
    "Tailor": "Service",
    "Instant Offices": "Service",
    "Health Club": "Service",
    "Travel": "Retail",
    "Car Rental": "Service",
    "Footwear": "Retail",
    "Laundary": "Service",
    "Financial Services": "Service",
    "Postal Office": "Service",
    "Wholesale": "Retail",
    "Exhibition": "Service",
    "Central Kitchen": "Foodservice",
    "Pharmacy": "Retail",
    "bakery": "Foodservice",
    "Stationary": "Service",
    "E-commerce": "Retail",
    "IT": "Service",
    "Scientific Instrument": "Retail",
    "Mini Market": "Retail",
    "Education": "Service",
    "Art": "Retail",
    "Taxi": "Service",
    "Community Services": "Service",
}

area_table = {
    "Refinery Ahmadi Port": "Ahmadi",
    "Addan": "Mubarak Al Kabeer",
    "Riqqa": "Ahmadi",
    "Surra": "Asimah",
    "Al Jahra Camps": "Jahra",
    "Ardiya": "Farwaniya",
    "Soor Gardens": "Asimah",
    "Naseem": "Jahra",
    "Qairawan": "Jahra",
    "Jleeb Al Shuyokh": "Farwaniya",
    "Abu Hasania": "Mubarak Al Kabeer",
    "Jahra Governorate Desert ": "Jahra",
    "Sulaibikhat": "Asimah",
    "Khaldiya": "Asimah",
    "Ishbiliya": "Farwaniya",
    "Central Ahmadi": "Ahmadi",
    "Ardiya Craft Area": "Farwaniya",
    "Fintas": "Ahmadi",
    "Coastal Strip": "Asimah",
    "Firdous": "Farwaniya",
    "Ali Sabah Al Salem": "Ahmadi",
    "Sabah Al Ahmad City 1": "Ahmadi",
    "Sabah Al Ahmad City 2": "Ahmadi",
    "Sulaibia Agricultural": "Jahra",
    "Airport Area": "Farwaniya",
    "Al Jahra": "Jahra",
    "Hadiya": "Ahmadi",
    "Shadadia": "Farwaniya",
    "Mina Abdullah": "Ahmadi",
    "Dahar": "Ahmadi",
    "North Western Sulaibikhat": "Asimah",
    "Salmiya": "Hawally",
    "Hateen": "Hawally",
    "Kabd": "Jahra",
    "Dasma": "Asimah",
    "Abu Fateera": "Mubarak Al Kabeer",
    "Mirqab": "Asimah",
    "Farwaniya": "Farwaniya",
    "Jaber Al-Ali": "Ahmadi",
    "Wafra New": "Ahmadi",
    "Mitlaa": "Jahra",
    "Sulaibia Industrial 2": "Jahra",
    "Al Shuhada": "Hawally",
    "Al Masayeel": "Mubarak Al Kabeer",
    "Adailiya": "Asimah",
    "Yarmouk": "Asimah",
    "Qurtuba": "Asimah",
    "Hawally": "Hawally",
    "Nuzha": "Asimah",
    "Jahra Industrial Craft 1": "Jahra",
    "Dasman": "Asimah",
    "Saad Al Abdullah": "Jahra",
    "Miqwaa": "Ahmadi",
    "Rabiya": "Farwaniya",
    "Doha": "Asimah",
    "Abdaly": "Jahra",
    "The Middle Area": "Mubarak Al Kabeer",
    "Dubaiya Chalets": "Ahmadi",
    "Salwa": "Hawally",
    "Qasr": "Jahra",
    "Anjifa": "Hawally",
    "Qibla": "Asimah",
    "Doha Port": "Asimah",
    "Julaia'a Chalets": "Ahmadi",
    "North West Jahra": "Jahra",
    "Manqaf": "Ahmadi",
    "Shuwaikh Industrial 3": "Asimah",
    "Sabah Al Ahmad Sea City": "Ahmadi",
    "Mansouriya": "Asimah",
    "Al Khairan Chalets": "Ahmadi",
    "Faiha": "Asimah",
    "Ministries Area": "Hawally",
    "North Ahmadi": "Ahmadi",
    "Daiya": "Asimah",
    "Shaab": "Hawally",
    "Salam": "Hawally",
    "Al Mubarakia": "Hawally",
    "Taima": "Jahra",
    "Ahmadi Governorate Desert": "Ahmadi",
    "Abdullah Al Salem": "Asimah",
    "Al Zour": "Ahmadi",
    "Abu Fateera Craft City": "Mubarak Al Kabeer",
    "Nuwaiseeb Chalets": "Ahmadi",
    "Nahda": "Jahra",
    "Alrawdatain": "Jahra",
    "Zahra": "Hawally",
    "Shuwaikh Residential": "Asimah",
    "Qadsia": "Asimah",
    "Khitan": "Farwaniya",
    "South Ahmadi": "Ahmadi",
    "Mubarak Al Kabeer": "Mubarak Al Kabeer",
    "Bneid Al Qar": "Asimah",
    "Fahaheel": "Ahmadi",
    "Wafra Farms": "Ahmadi",
    "Sharq": "Asimah",
    "Mubarak Al Abdullah": "Hawally",
    "Mahboula": "Ahmadi",
    "Qurain": "Mubarak Al Kabeer",
    "Western Shuaiba Industrial": "Ahmadi",
    "Al-Siddeeq": "Hawally",
    "Ghirnada": "Asimah",
    "Mubarakia Camp": "Asimah",
    "Abdullah Al Mubarak": "Farwaniya",
    "Al Zour Chalets": "Ahmadi",
    "Sabah Al Ahmad City 5": "Ahmadi",
    "Rihab": "Farwaniya",
    "Qosoor": "Mubarak Al Kabeer",
    "Rawda": "Asimah",
    "Maseela": "Mubarak Al Kabeer",
    "Bnaider Chalets": "Ahmadi",
    "Sabah Healthcare City": "Asimah",
    "Salmy": "Jahra",
    "Ardiya 4": "Farwaniya",
    "Jabriya": "Hawally",
    "Rumaithiya": "Hawally",
    "Funaitees": "Mubarak Al Kabeer",
    "Dhajeej": "Farwaniya",
    "Shuwaikh Industrial 1": "Asimah",
    "Eqaila": "Ahmadi",
    "Shamiya": "Asimah",
    "Bida’a": "Hawally",
    "Sabahiya": "Ahmadi",
    "Sabah Al Salem": "Mubarak Al Kabeer",
    "Ardiya 6": "Farwaniya",
    "Bayan": "Hawally",
    "Sulaibia": "Jahra",
    "Kifan": "Asimah",
    "Alrai": "Farwaniya",
    "East Ahmadi": "Ahmadi",
    "Mishrif": "Hawally",
    "Subia": "Jahra",
    "Fahad Al Ahmad": "Ahmadi",
    "Reggae": "Farwaniya",
    "Oyoon": "Jahra",
    "Sabah Al Naser": "Farwaniya",
    "Andalus": "Farwaniya",
    "Jabir Al Ahmad City": "Asimah",
    "Shuwaikh Industrial 2": "Asimah",
    "Abu Halifa": "Ahmadi",
    "Sabah Al Ahmad City 3": "Ahmadi",
    "Sabah Al Ahmad City 4": "Ahmadi",
    "Omarya": "Farwaniya",
}
